### ISSUE TITLE
测试case出现比对结果错误

### ISSUE THREAD

**Issue by zhangyulin** [adleida/adx-nodejs#3]
测试/home/ubuntu/TestCase/right/not_full_feild_response/008 时,
发现比对结果错误,,人工比对发现exchange返回两个结果,case里有三个结果
之后再次测试发现又比对成功了,,在次查看log 发现返回的两个结果是一家dsp的,
可能是另一家的结果没有被exchange收到,建议exchange的log里 把哪家dsp发送的打印出来

**Comment by lkiversonlk** [comment]
请贴上log。
